AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM Template for Ichor Products

Parameters:
  Stage:
    Type: String
    Default: prod

Globals:
  Function:
    Runtime: python3.8
    Timeout: 120

Resources:
  ApiDeployment:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Stage

  ProductsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: products/
      FunctionName: products
      Handler: app.lambda_handler
      Events:
        GetProducts:
          Type: Api
          Properties:
            Path: /products
            Method: get
            RestApiId: !Ref ApiDeployment
        GetProduct:
          Type: Api
          Properties:
            Path: /product/{internalName}
            Method: get
            RestApiId: !Ref ApiDeployment
      Policies:
        - DynamoDBReadPolicy: { TableName: products }

  ProductsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: products
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: internalName
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: internalName
          KeySchema:
            - AttributeName: internalName
              KeyType: HASH
          Projection:
            ProjectionType: "ALL"
